export const QUERY_KEYS = {
    GROUPS: "GROUPS", // + GROUPID
    MOVIE_NIGHT_EVENTS: "MOVIE_NIGHT_EVENTS", // + GROUPiD
    CHAT_MSG: "CHAT_MSG", // + MOVIENIGHT_EVENTID
    USER: "USER",
    MEMBERS: "MEMBERS", // + GROUPID
    TMDB_MOVIES: "TMDB_MOVIES" // + QUERY
}