export const QUERY_KEYS = {
    GROUPS: "GROUPS", // + USER_ID
    MOVIE_NIGHT_EVENTS: "MOVIE_NIGHT_EVENTS", // + GROUP_ID
    CHAT_MSG: "CHAT_MSG", // + MOVIENIGHT_EVENTID
    USER: "USER",
    MEMBERS: "MEMBERS", // + GROUP_ID
    TMDB_MOVIES: "TMDB_MOVIES", // + QUERY
    MOVIE_SUGGESTIONS: "MOVIE_SUGGESTIONS", // + MOVIENIGHT_EVENTID
    GROUP_INVITES: "GROUP_INVITES", // + USER_ID + GROUP_ID
    GROUPS_TO_JOIN: "GROUPS_TO_JOIN", // + QUERY
    USERS_TO_INVITE: "USERS_TO_INVITE"  // + QUERY + GROUP_ID
}