// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchHive.Models;

#nullable disable

namespace WatchHive.Migrations
{
    [DbContext(typeof(WatchHiveDbContext))]
    partial class WatchHiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchHive.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MovieNightEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 4, 14, 19, 19, 18, 333, DateTimeKind.Utc).AddTicks(5607));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieNightEventId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages", "app");
                });

            modelBuilder.Entity("WatchHive.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name", "CreatedById")
                        .IsUnique();

                    b.ToTable("Groups", "app");
                });

            modelBuilder.Entity("WatchHive.Models.GroupInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviteeUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GroupId");

                    b.HasIndex("InviteeUserId");

                    b.ToTable("GroupInvitations", "app");
                });

            modelBuilder.Entity("WatchHive.Models.Movie", b =>
                {
                    b.Property<int>("TmdbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TmdbId"));

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("double precision");

                    b.HasKey("TmdbId");

                    b.ToTable("Movies", "app");
                });

            modelBuilder.Entity("WatchHive.Models.MovieNightEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SelectedMovieId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GroupId");

                    b.HasIndex("SelectedMovieId");

                    b.ToTable("MovieNightEvents", "app");
                });

            modelBuilder.Entity("WatchHive.Models.MovieNightRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieNightEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieNightEventId");

                    b.HasIndex("UserId", "MovieNightEventId")
                        .IsUnique();

                    b.ToTable("MovieNightRatings", "app");
                });

            modelBuilder.Entity("WatchHive.Models.MoviePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MoviePreferences", "app");
                });

            modelBuilder.Entity("WatchHive.Models.MovieSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisqualified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MovieNightEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuggestedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("SuggestedById");

                    b.HasIndex("MovieNightEventId", "MovieId")
                        .IsUnique();

                    b.ToTable("MovieSuggestions", "app");
                });

            modelBuilder.Entity("WatchHive.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Expires");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRevoked", "Expires");

                    b.ToTable("RefreshTokens", "app");
                });

            modelBuilder.Entity("WatchHive.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 175, DateTimeKind.Unspecified).AddTicks(9568), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 175, DateTimeKind.Unspecified).AddTicks(9568), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleValue = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 175, DateTimeKind.Unspecified).AddTicks(9568), new TimeSpan(0, 0, 0, 0, 0)),
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 175, DateTimeKind.Unspecified).AddTicks(9568), new TimeSpan(0, 0, 0, 0, 0)),
                            RoleValue = 2
                        });
                });

            modelBuilder.Entity("WatchHive.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 178, DateTimeKind.Unspecified).AddTicks(6399), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@sys.com",
                            EmailVerified = true,
                            FullName = "System Administrator",
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 178, DateTimeKind.Unspecified).AddTicks(6399), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$ki0D4Slmc17DcM2VZqv4nu1H7FpDtopYtqd2b.xMPc.TQdgkktL8W",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "john@app.com",
                            EmailVerified = true,
                            FullName = "John Doe",
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$v/M8cg.gcuS1IwIWpGLMCeHSc.4FBFe.QxUZ0bmva5wHP4/H2mVpy",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "jane@app.com",
                            EmailVerified = true,
                            FullName = "Jane Doe",
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$HrCPmdY47s3/NlfXAhyEU.YpoywHi23V.ynIYRn6BqHDAw7FKPL/i",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Created = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "po@app.com",
                            EmailVerified = true,
                            FullName = "Dragon Warrior",
                            LastModified = new DateTimeOffset(new DateTime(2026, 4, 14, 19, 19, 17, 562, DateTimeKind.Unspecified).AddTicks(8941), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$242DWiD4YAHz8lz33aprzeTszJPXE45g9f.8oHAaGHYeVrRa.PV0K",
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("WatchHive.Models.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroups", "app");
                });

            modelBuilder.Entity("WatchHive.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovieSuggestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VoteType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieSuggestionId");

                    b.HasIndex("UserId", "MovieSuggestionId")
                        .IsUnique();

                    b.ToTable("Votes", "app");
                });

            modelBuilder.Entity("WatchHive.Models.ChatMessage", b =>
                {
                    b.HasOne("WatchHive.Models.MovieNightEvent", "MovieNightEvent")
                        .WithMany("ChatMessages")
                        .HasForeignKey("MovieNightEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "SentBy")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MovieNightEvent");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("WatchHive.Models.Group", b =>
                {
                    b.HasOne("WatchHive.Models.User", "CreatedBy")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("WatchHive.Models.GroupInvitation", b =>
                {
                    b.HasOne("WatchHive.Models.User", "CreatedBy")
                        .WithMany("InvitationsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.Group", "Group")
                        .WithMany("GroupInvitations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "Invitee")
                        .WithMany("InvitationRequests")
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");

                    b.Navigation("Invitee");
                });

            modelBuilder.Entity("WatchHive.Models.MovieNightEvent", b =>
                {
                    b.HasOne("WatchHive.Models.User", "CreatedBy")
                        .WithMany("MovieNightEvents")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.Group", "Group")
                        .WithMany("MovieNightEvents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.Movie", "SelectedMovie")
                        .WithMany("MovieNightEvents")
                        .HasForeignKey("SelectedMovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Group");

                    b.Navigation("SelectedMovie");
                });

            modelBuilder.Entity("WatchHive.Models.MovieNightRating", b =>
                {
                    b.HasOne("WatchHive.Models.MovieNightEvent", "MovieNightEvent")
                        .WithMany("MovieNightRatings")
                        .HasForeignKey("MovieNightEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "User")
                        .WithMany("MovieNightRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MovieNightEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchHive.Models.MoviePreference", b =>
                {
                    b.HasOne("WatchHive.Models.User", "User")
                        .WithMany("MoviePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchHive.Models.MovieSuggestion", b =>
                {
                    b.HasOne("WatchHive.Models.Movie", "Movie")
                        .WithMany("MovieSuggestions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.MovieNightEvent", "MovieNightEvent")
                        .WithMany("MovieSuggestions")
                        .HasForeignKey("MovieNightEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "SuggestedBy")
                        .WithMany("MovieSuggestions")
                        .HasForeignKey("SuggestedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieNightEvent");

                    b.Navigation("SuggestedBy");
                });

            modelBuilder.Entity("WatchHive.Models.RefreshToken", b =>
                {
                    b.HasOne("WatchHive.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchHive.Models.User", b =>
                {
                    b.HasOne("WatchHive.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WatchHive.Models.UserGroup", b =>
                {
                    b.HasOne("WatchHive.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchHive.Models.Vote", b =>
                {
                    b.HasOne("WatchHive.Models.MovieSuggestion", "MovieSuggestion")
                        .WithMany("Votes")
                        .HasForeignKey("MovieSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchHive.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MovieSuggestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WatchHive.Models.Group", b =>
                {
                    b.Navigation("GroupInvitations");

                    b.Navigation("Members");

                    b.Navigation("MovieNightEvents");
                });

            modelBuilder.Entity("WatchHive.Models.Movie", b =>
                {
                    b.Navigation("MovieNightEvents");

                    b.Navigation("MovieSuggestions");
                });

            modelBuilder.Entity("WatchHive.Models.MovieNightEvent", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("MovieNightRatings");

                    b.Navigation("MovieSuggestions");
                });

            modelBuilder.Entity("WatchHive.Models.MovieSuggestion", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("WatchHive.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WatchHive.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("CreatedGroups");

                    b.Navigation("InvitationRequests");

                    b.Navigation("InvitationsCreated");

                    b.Navigation("MovieNightEvents");

                    b.Navigation("MovieNightRatings");

                    b.Navigation("MoviePreferences");

                    b.Navigation("MovieSuggestions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserGroups");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
